// Mock data generated by GPT

export const SIMULATION_DATA = {
    agents: [
        {
            id: 1,
            name: "Buyer",
            position: [-2, 0, 0],
            rotation: [0, Math.PI / 2, 0],
            model: "../../models/female-character.glb"
        },
        {
            id: 2,
            name: "Salesperson",
            position: [2, 0, 0],
            rotation: [0, -Math.PI / 2, 0],
            model: "../../models/male-character.glb"
        }
    ],
    conversation: [
        {
            speakerId: 1,
            text: "Hi, I'm interested in the 2024 Model X SUV I saw on your website.",
        },
        {
            speakerId: 2,
            text: "Welcome! The Model X is an excellent choice. It's listed at $45,000. Would you like to take a closer look?",
        },
        {
            speakerId: 1,
            text: "Yes, but $45,000 is a bit over my budget. I was hoping to stay closer to $40,000.",
        },
        {
            speakerId: 2,
            text: "I understand. Given the current market conditions, I could offer it at $43,500. It comes with a premium package worth $2,000.",
        },
        {
            speakerId: 1,
            text: "That's still high. What if I pay in cash? Would you consider $41,000?",
        },
        {
            speakerId: 2,
            text: "Cash is appealing. I can work with that. How about we meet in the middle at $42,000? I'll also include a 3-year maintenance package.",
        },
        {
            speakerId: 1,
            text: "That maintenance package sounds good. Could you throw in all-weather floor mats too?",
        },
        {
            speakerId: 2,
            text: "Deal! $42,000 with the maintenance package and floor mats. Would you like to proceed with the paperwork?",
        },
        {
            speakerId: 1,
            text: "Perfect! Yes, let's finalize everything.",
        },
        {
            speakerId: 2,
            text: "Excellent choice! I'll prepare the documents right away. You've got yourself a great deal!",
        }
    ]
};
